---

- hosts: all
  gather_facts: no

  tasks:
    - name: Install LAMP
      yum:
        name: ["wget","httpd"]
        state: present
    - name: Install package from survey
      yum:
        name: postfix
        state: present


