---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

   - name: Launch RHEL 8.8 EC2 Instance. With base additional volume. 
     ec2:
       group: launch-wizard-1
       instance_type: "{{ instance_type }}"
       image: "{{ ami }}"
       wait: true
       region: "{{ region }}"
       keypair: linux-box2
       count: 1
       vpc_subnet_id: "{{ vpc_subnet_id }}"
       assign_public_ip: yes
       volumes:
         - device_name: "{{ device_name0 }}"
           volume_size: "{{ volume_size0 }}"
           delete_on_termination: true
       user_data: |
          #!/usr/bin/bash
          rm -rf /etc/redhat-release
       instance_tags:
         Name: "{{ servername }}"
         DeploymentType: Ansible Tower
     register: ec2
     retries: 5
     delay: 10
     until: ec2 is not failed
     tags:
       - linux

   - name: Wait for ssh connection 
     wait_for:
       host: "{{ item.public_ip }}"
       port: 22 
       state: started 
     loop: "{{ ec2.instances }}"
     tags:
      - linux

   - name: Creating Windows instance
     ec2:
       group: default
       instance_type: t2.micro
       image: "{{ ec2_ami }}"
       wait: true
       region: "{{ region }}"
       volumes:
         - device_name: "{{ device_name0 }}"
           volume_size: 30
       count: 1
       user_data: |
         <powershell>
         $admin = [adsi]("WinNT://./administrator, user")
         $admin.PSBase.Invoke("SetPassword", "{{ winlocal_admin_pass }}")
         Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
         </powershell>
       vpc_subnet_id: "{{ vpc_subnet_id }}"
       instance_tags:
         "CostCode": "{{ costcode }}"
         "Name": "{{ ap_servername }}"
     register: ec2win
     retries: 5
     delay: 10
     until: ec2win is not failed

    - name: Wait for system to become reachable over WinRM
      wait_for_connection:
        timeout: 900

    - name: Register host to list
      add_host:
         hostname: "{{ item.public_ip }}"
         groups: Windows
      loop: "{{ ec2win.instances }}"


- name: Run tasks on Windows 
  hosts: Windows

  gather_facts: False
  tasks:
     - name: Run netstat command
       win_command: netstat -e
       register: netstat

     - debug:
         var: netstat