--- 

- name: Run tasks on Windows 
  hosts: all

  gather_facts: False
  tasks:
     - name: Run netstat command
       win_command: netstat -e
       register: netstat

     - debug:
         var: netstat

         