---

- hosts: all
  connection: local
  gather_facts: false
  vars:
    provider:
      password: "{{ bigip_pass }}"
      server: 192.168.122.138
      user: admin
      validate_certs: no
      server_port: 8443
    pool_name: []
    node_name: []

  tasks:
    - name: Register facts for F5 device
      bigip_device_facts:
        gather_subset:
          - nodes
          - ltm-pools
        provider: "{{ provider }}"
      delegate_to: localhost
      changed_when: false
      register: stat

    - name: Set facts for existing pools and node names. 
      set_fact:
        pool_name: "{{ pool_name}} + [ '{{  item.0.name }}' ]"
        node_name: "{{ node_name }}  + [ '{{item.1.name }}' ]"
      with_nested:
        - "{{ stat.ltm_pools }}"
        - "{{ stat.nodes }}"
      loop_control:
        label: "{{ item.0.name }}"

    - name: Run the roles only if pools and nodes are not existing
      block:
       - include_role:
           name: create_pool
       - include_role:
           name: create_node
       - include_role:
           name: add_member
       - include_role:
           name: add_vip
      when:
       - pname not in pool_name
       - nname not in node_name