- name: Configure BigIP pool
  hosts: all
  gather_facts: false
  vars:
    provider:
      password: "{{ bigip_pass }}"
      server: 192.168.122.138
      user: admin
      validate_certs: no
      server_port: 8443
  tasks:
    - name: Register all nodes that exist on Bigip
      bigip_device_facts:
        gather_subset:
          - nodes
        provider: "{{ provider }}"
      delegate_to: localhost
      register: stat

    - name: Create node if it doesn't exist
      bigip_node:
        host: "{{ ip }}"
        name: "{{ ipname }}"
        provider: "{{ provider }}"
        partition: Common
      delegate_to: localhost


    - name: Create pool if pool doesn't exist
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: "{{ pname }}"
        slow_ramp_time: 120
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
       provider: "{{ provider }}"
       description: "testserver {{ ip }}"
       host: "{{ ip }}"
       name: "{{ ipname }}"
       pool: "{{ pname  }}"
       port: 80

# adding one change
