- name: Configure BigIP pool
  hosts: all
  gather_facts: false
  vars:
    provider:
      password: "{{ bigip_pass }}"
      server: 192.168.122.138
      user: admin
      validate_certs: no
      server_port: 8443
  tasks:
    - name: Register all nodes that exist on Bigip
      bigip_device_facts:
        gather_subset:
          - nodes
          - ltm-pools
        provider: "{{ provider }}"
      delegate_to: localhost
      register: stat
    
    - name: End playbook if the node/pool already exists
      fail:
        msg: Ending Playbook due to duplicate node/pool names
      when:
         - ipname == item.0.name
         - pname == item.1.name
      with_nested:
          - "{{ stat2.nodes }}"
          - "{{ stat2.ltm_pools }}"
      loop_control:
        label: "{{ item.0.name }}"

    - name: Create node if it doesn't exist
      bigip_node:
        host: "{{ ip }}"
        name: "{{ ipname }}"
        provider: "{{ provider }}"
        partition: Common
      delegate_to: localhost


    - name: Create pool if pool doesn't exist
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: "{{ pname }}"
        slow_ramp_time: 120
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
       provider: "{{ provider }}"
       description: "testserver" 
       host: "{{ ip }}"
       name: "{{ ipname }}"
       pool: "{{ pname  }}"
       port: 80

    - name: Add virtual server addresses
      bigip_virtual_server:
        state: present
        partition: Common
        name: "{{ vname }}"
        destination: "{{ dip }}"
        type: "{{ type }}"
        port: 443
        pool: apache
        snat: Automap
        description: Test Virtual Server
        provider: "{{ provider }}"
        ip_protocol: "{{ type }}"
        profiles:
          - name: fastL4
      delegate_to: localhost
