---
- hosts: all
  gather_facts: false
  vars:
    provider:
      password: "{{ bigip_pass }}"
      server: 192.168.122.138
      user: admin
      validate_certs: no
      server_port: 8443

  tasks:
    - name: "Ping module to be added"
      uri:
        url: https://192.168.122.191/api/v2/job_templates/12/survey_spec/
        user: admin
        password: redhat
        method: POST
        body: "{{ lookup('file','issue.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: no 
