---
- hosts: all
  gather_facts: false
  vars:
   create:
      json:
        info:
          - {key: 'key_1', value: '8308a020-5c9d-4936-8f1a-40f408d3a085'}

  tasks:
    - template:
        src: issue.j2
        dest: issue.json
    - name: "Ping module to be added"
      uri:
        url: https://192.168.122.191/api/v2/job_templates/12/survey_spec/
        user: admin
        password: redhat
        method: POST
        body: "{{ lookup('file','issue.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: no 
