---
- hosts: all
  gather_facts: false
  vars:
    provider:
      password: "{{ bigip_pass }}"
      server: 192.168.122.138
      user: admin
      validate_certs: no
      server_port: 8443

  tasks:
    - name: "Ping"
      tower_job_template:
         job_type: "run"
         inventory: "Local"
         project: "Git hub"
         playbook: "05-bigip.yml"
         name: "Simple Survey"
         state: "present"
  #       tower_config_file: "~/tower_cli.cfg"
         survey_enabled: yes
         survey_spec: "{{ lookup('file', 'my_survey.json') }}"
