---

- name: Add virtual server addresses
  bigip_virtual_server:
    state: present
    partition: Common
    name: "{{ vname }}"
    destination: "{{ dip }}"
    type: "{{ type }}"
    port: 443
    pool: "{{ pname }}"
    snat: Automap
    description: Test Virtual Server
    provider: "{{ provider }}"
    ip_protocol: "{{ protocol }}"
    profiles:
      - name: fastL4
  when: type == "performance-l4"


- name: Add virtual server addresses
  bigip_virtual_server:
    state: present
    partition: Common
    name: "{{ vname }}"
    destination: "{{ dip }}"
    type: "{{ type }}"
    port: 443
    pool: "{{ pname }}"
    snat: Automap
    description: Test Virtual Server
    provider: "{{ provider }}"
    ip_protocol: "{{ protocol }}"
  when: type is search("standard")