---


- name: KVM | VM Creation | Grab a list of defined VMs
  shell: virsh list --all --name
  changed_when: false
  register: kvm_vm_list
  tags:
    - deploy_vim
    - kvm
    - vm_create

- name: OS | Debug | Operation if satellite exists
  shell: touch /tmp/satellite123
  when:
    - kvm_vm_list.stdout.find('satellite') == -1

- name: OS | Debug | Operation if guest exists
  shell: touch /tmp/guest123
  when:
    - kvm_vm_list.stdout.find('guest') == -1
